vim.g.colors_name = "vesper"

vim.o.termguicolors = true

vim.cmd.highlight("clear")

if vim.fn.exists("syntax_on") then
	vim.cmd.syntax("reset")
end

local colors = {
	green = "#99FFE4",
	neutral_900 = "#101010",
	neutral_800 = "#161616",
	neutral_700 = "#1C1C1C",
	neutral_600 = "#505050",
	neutral_500 = "#707070",
	neutral_400 = "#7E7E7E",
	neutral_300 = "#A0A0A0",
	orange = "#FFC799",
	red = "#FF8080",
	white = "#FFFFFF",
}

local groups = {
	Added = { fg = colors.green },
	Attribute = {},
	Bold = {},
	Boolean = {},
	Changed = {},
	Character = {},
	Class = {},
	-- CmpItemAbbr = {},
	-- CmpItemAbbrDeprecated = {},
	-- CmpItemAbbrMatch = {},
	-- CmpItemAbbrMatchFuzzy = {},
	-- CmpItemKind = {},
	-- CmpItemKindClass = {},
	-- CmpItemKindColor = {},
	-- CmpItemKindConstant = {},
	-- CmpItemKindConstructor = {},
	-- CmpItemKindCopilot = {},
	-- CmpItemKindEnum = {},
	-- CmpItemKindEnumMember = {},
	-- CmpItemKindEvent = {},
	-- CmpItemKindField = {},
	-- CmpItemKindFile = {},
	-- CmpItemKindFolder = {},
	-- CmpItemKindFunction = {},
	-- CmpItemKindInterface = {},
	-- CmpItemKindKeyword = {},
	-- CmpItemKindMethod = {},
	-- CmpItemKindModule = {},
	-- CmpItemKindOperator = {},
	-- CmpItemKindProperty = {},
	-- CmpItemKindReference = {},
	-- CmpItemKindSnippet = {},
	-- CmpItemKindStruct = {},
	-- CmpItemKindText = {},
	-- CmpItemKindTypeParameter = {},
	-- CmpItemKindUnit = {},
	-- CmpItemKindValue = {},
	-- CmpItemKindVariable = {},
	-- CmpItemMenu = {},
	ColorColumn = {},
	Comment = { fg = colors.orange },
	Conceal = {},
	Conditional = {},
	Constant = {},
	CurSearch = { link = "Search" },
	Cursor = { bg = colors.white, fg = colors.neutral_700 },
	CursorColumn = {},
	CursorIM = { link = "Cursor" },
	CursorLine = { bg = colors.neutral_700 },
	CursorLineFold = {},
	CursorLineNr = { link = "CursorLine" },
	CursorLineSign = {},
	Debug = {},
	Define = {},
	Deleted = { fg = colors.red },
	Delimiter = {},
	DiagnosticDeprecated = {},
	DiagnosticError = {},
	DiagnosticFloatingError = {},
	DiagnosticFloatingHint = {},
	DiagnosticFloatingInfo = {},
	DiagnosticFloatingOk = {},
	DiagnosticFloatingWarn = {},
	DiagnosticHint = {},
	DiagnosticInfo = {},
	DiagnosticOk = {},
	DiagnosticSignError = { fg = colors.red },
	DiagnosticSignHint = { fg = colors.neutral_600 },
	DiagnosticSignInfo = { fg = colors.neutral_600 },
	DiagnosticSignOk = { fg = colors.green },
	DiagnosticSignWarn = { fg = colors.orange },
	DiagnosticUnderlineError = {},
	DiagnosticUnderlineHint = {},
	DiagnosticUnderlineInfo = {},
	DiagnosticUnderlineOk = {},
	DiagnosticUnderlineWarn = {},
	DiagnosticUnnecessary = {},
	DiagnosticVirtualTextError = { fg = colors.red },
	DiagnosticVirtualTextHint = { fg = colors.neutral_600 },
	DiagnosticVirtualTextInfo = { fg = colors.neutral_600 },
	DiagnosticVirtualTextOk = { fg = colors.green },
	DiagnosticVirtualTextWarn = { fg = colors.orange },
	DiagnosticWarn = {},
	DiffAdd = { link = "Added" },
	DiffChange = { link = "Changed" },
	DiffDelete = { link = "Deleted" },
	DiffText = {},
	Directory = { fg = colors.green },
	EndOfBuffer = {},
	Error = { fg = colors.red },
	ErrorMsg = { link = "Error" },
	Exception = {},
	Field = {},
	Float = { bg = colors.neutral_700 },
	FloatBorder = { bg = colors.neutral_700, fg = colors.neutral_700 },
	FloatFooter = {},
	FloatShadow = {},
	FloatShadowThrough = {},
	FloatTitle = {},
	FoldColumn = {},
	Folded = {},
	Function = {},
	GitGutterAddLineNr = {},
	GitGutterChangeLineNr = {},
	GitGutterDeleteLineNr = {},
	GitSignsAdd = { fg = colors.green },
	GitSignsAddInline = { link = "GitSignsAdd" },
	GitSignsAddLn = { link = "GitSignsAdd" },
	GitSignsAddLnInline = { link = "GitSignsAdd" },
	GitSignsAddNr = { link = "GitSignsAdd" },
	GitSignsAddPreview = { link = "GitSignsAdd" },
	GitSignsChange = { fg = colors.orange },
	GitSignsChangeInline = { link = "GitSignsChange" },
	GitSignsChangeLn = { link = "GitSignsChange" },
	GitSignsChangeLnInline = { link = "GitSignsChange" },
	GitSignsChangeNr = { link = "GitSignsChange" },
	GitSignsChangedelete = {},
	GitSignsChangedeleteLn = {},
	GitSignsChangedeleteNr = {},
	GitSignsCurrentLineBlame = {},
	GitSignsDelete = { fg = colors.red },
	GitSignsDeleteInline = { link = "GitSignsDelete" },
	GitSignsDeleteLnInline = { link = "GitSignsDelete" },
	GitSignsDeleteNr = { link = "GitSignsDelete" },
	GitSignsDeletePreview = { link = "GitSignsDelete" },
	GitSignsDeleteVirtLn = {},
	GitSignsDeleteVirtLnInLine = {},
	GitSignsStagedAdd = { link = "GitSignsAdd" },
	GitSignsStagedAddLn = { link = "GitSignsAdd" },
	GitSignsStagedAddNr = { link = "GitSignsAdd" },
	GitSignsStagedChange = {},
	GitSignsStagedChangeLn = {},
	GitSignsStagedChangeNr = {},
	GitSignsStagedChangedelete = {},
	GitSignsStagedChangedeleteLn = {},
	GitSignsStagedChangedeleteNr = {},
	GitSignsStagedDelete = { link = "GitSignsDelete" },
	GitSignsStagedDeleteNr = { link = "GitSignsDelete" },
	GitSignsStagedTopdelete = { link = "GitSignsDelete" },
	GitSignsStagedTopdeleteNr = { link = "GitSignsDelete" },
	GitSignsTopdelete = { link = "GitSignsDelete" },
	GitSignsTopdeleteNr = { link = "GitSignsDelete" },
	GitSignsUntracked = {},
	GitSignsUntrackedLn = {},
	GitSignsUntrackedNr = {},
	GitSignsVirtLnum = {},
	Identifier = {},
	Ignore = {},
	IncSearch = { link = "Search" },
	Include = {},
	Italic = {},
	Keyword = {},
	Label = {},
	LazyH1 = { bg = colors.orange, fg = colors.neutral_700 },
	LazyNormal = { link = "Float" },
	LineNr = {},
	LineNrAbove = { fg = colors.neutral_600 },
	LineNrBelow = { fg = colors.neutral_600 },
	LspCodeLens = {},
	LspCodeLensSeparator = {},
	LspInlayHint = { fg = colors.neutral_600 },
	LspReferenceRead = {},
	LspReferenceText = {},
	LspReferenceWrite = {},
	LspSignatureActiveParameter = { fg = colors.neutral_600 },
	Macro = {},
	-- MasonError = {},
	MasonHeader = { bg = "NONE", fg = colors.orange },
	MasonHeaderSecondary = { bg = colors.green, bold = true, fg = colors.white },
	-- MasonHeading = {},
	MasonHighlight = { fg = colors.green },
	MasonHighlightBlock = { bg = colors.orange, fg = colors.neutral_700 },
	MasonHighlightBlockBold = { bg = colors.orange, bold = true, fg = colors.neutral_700 },
	MasonHighlightBlockBoldSecondary = { bg = colors.orange, bold = true, fg = colors.neutral_700 },
	MasonHighlightBlockSecondary = { bg = colors.orange, fg = colors.white },
	MasonHighlightSecondary = { fg = colors.orange },
	MasonLink = { fg = colors.green },
	MasonMuted = { fg = colors.neutral_600 },
	MasonMutedBlock = { bg = colors.neutral_600, fg = colors.neutral_700 },
	MasonMutedBlockBold = { bg = colors.neutral_600, bold = true, fg = colors.neutral_700 },
	MasonNormal = { link = "Float" },
	-- MasonWarning = {},
	MatchParen = {},
	Method = {},
	ModeMsg = { fg = colors.orange },
	MoreMsg = {},
	MsgArea = {},
	MsgSeparator = {},
	NonText = {},
	Normal = { bg = colors.neutral_900, fg = colors.white },
	NormalFloat = { bg = colors.neutral_700, fg = colors.neutral_300 },
	NormalNC = { bg = "#000000", fg = colors.neutral_500 },
	Number = {},
	Operator = {},
	Parameter = {},
	Pmenu = { bg = colors.neutral_700, fg = colors.neutral_600 },
	PmenuExtra = {},
	PmenuExtraSel = {},
	PmenuKind = {},
	PmenuKindSel = {},
	PmenuSbar = { bg = colors.neutral_700 },
	PmenuSel = { bg = colors.neutral_600, fg = colors.white },
	PmenuThumb = { bg = colors.neutral_500 },
	PreCondit = {},
	PreProc = {},
	Property = {},
	Punctuation = {},
	Question = {},
	QuickFixLine = {},
	RedrawDebugClear = {},
	RedrawDebugComposed = {},
	RedrawDebugNormal = {},
	RedrawDebugRecompose = {},
	Removed = {},
	Repeat = {},
	Search = { link = "Visual" },
	SignColumn = {},
	SnippetTabstop = {},
	Special = {},
	SpecialChar = {},
	SpecialComment = {},
	SpecialKey = {},
	SpellBad = {},
	SpellCap = {},
	SpellLocal = {},
	SpellRare = {},
	Statement = {},
	StatusLine = { bg = colors.neutral_900, fg = colors.neutral_300 },
	StatusLineNC = {},
	StorageClass = {},
	String = { fg = colors.green },
	Struct = {},
	Structure = {},
	Substitute = {},
	TabLine = { bg = colors.neutral_900 },
	TabLineFill = {},
	TabLineSel = { bg = colors.neutral_800 },
	Tag = {},
	TermCursor = { bg = colors.neutral_500, fg = colors.neutral_700 },
	TermCursorNC = { bg = colors.neutral_700, fg = colors.neutral_400 },
	Title = {},
	Todo = { fg = colors.neutral_300, bg = colors.neutral_700 },
	Type = {},
	Typedef = {},
	Underlined = {},
	VertSplit = {},
	Visual = { bg = colors.neutral_600, fg = colors.white },
	VisualNC = {},
	VisualNOS = {},
	WarningMsg = {},
	Whitespace = {},
	WildMenu = {},
	WinBar = {},
	WinBarNC = {},
	WinSeparator = {},
	lCursor = { link = "Cursor" },
	["@variable"] = {},
}

for group, parameters in pairs(groups) do
	vim.api.nvim_set_hl(0, group, parameters)
end
